//get MATCHES
export const SAVE_MATCH_FULLFILLED = 'SAVE_MATCH_FULLFILLED';
export const SAVE_MATCH_LOADING = 'SAVE_MATCH_LOADING';
export const SAVE_MATCH_REJECTED = 'SAVE_MATCH_REJECTED';

//add MATCH
export const ADD_MATCH_FULLFILLED = 'ADD_MATCH_FULLFILLED';
export const ADD_MATCH_LOADING = 'ADD_MATCH_LOADING';
export const ADD_MATCH_REJECTED = 'ADD_MATCH_REJECTED';

//edit MATCH
export const EDIT_MATCH_FULLFILLED = 'EDIT_MATCH_FULLFILLED';
export const EDIT_MATCH_LOADING = 'EDIT_MATCH_LOADING';
export const EDIT_MATCH_REJECTED = 'EDIT_MATCH_REJECTED';

//delete MATCH
export const DELETE_MATCH_FULLFILLED = 'DELETE_MATCH_FULLFILLED';
export const DELETE_MATCH_LOADING = 'DELETE_MATCH_LOADING';
export const DELETE_MATCH_REJECTED = 'DELETE_MATCH_REJECTED';